
name: Build and test

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    uses: Roadhog360/Hog-Actions-Workflows/.github/workflows/build-and-test.yml@master
    secrets: inherit
    # with:
    #   client-only: true
    # Uncomment for client-only mods
